### ISSUE TITLE
no https

### ISSUE THREAD

**Issue by everydaylearner** [rionshin/HomeKitInfluxGrafana#1]
I have question around HTTPS requirement: 

is there a way to bypass https? not getting a certificate when sending data to influxdb?

**Comment by rionshin** [comment]
> I have question around HTTPS requirement:
> 
> is there a way to bypass https? not getting a certificate when sending data to influxdb?

Unfortunately that’s standard and Apple is following it and do NOT allow connection to http addresses .  You can use some of free certificates but you need to have one.
